services:
  db:
    image: mysql
    container_name: geo-db
    environment:
      MYSQL_ROOT_PASSWORD: extremely-secure-password
    ports:
      - 33060:3306
    healthcheck:
      test: mysqladmin ping -u root -p"extremely-secure-password"
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: geo-server
    environment:
      IPSTACK_ACCESS_KEY: DEFINE_YOUR_API_KEY_HERE
    volumes:
      - ./:/app
    network_mode: host
    entrypoint: ./entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
